from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def write_document(self, section_slug: str, doc_slug: str, content: str, title: str = "", order: int = 0) -> None: ...
    async def delete_document(self, section_slug: str, doc_slug: str) -> None: ...
    async def save_image(self, filename: str, data: bytes) -> str: ...
